### ISSUE TITLE
Wrong avatars on feed

### ISSUE THREAD

**Issue by Molefas** [Cloudoki/appdoki-rn#18] opened 2020-11-27 06:33 UTC
On the feed homescreen, some avatars are wrong even though the names are correct.
![File](https://user-images.githubusercontent.com/5502039/100418312-79a60980-307a-11eb-851f-3b41140acea9.jpg)

**Comment by mstrk** [comment] 2020-11-27 12:32
Duplicate of #10

**Closed as completed by mstrk** 2020-11-27 12:32 UTC
Labels: bug, duplicate
